"""Pre-built Part 1 question palettes — no LLM call needed."""
from __future__ import annotations

QUESTION_BANK: dict[str, list[str]] = {
    "hometown": [
        "Where are you from originally?",
        "Do you still live in your hometown?",
        "What do you like most about your hometown?",
        "What is your hometown famous for?",
        "Has your hometown changed much in recent years?",
        "Would you recommend visitors to come to your hometown? Why?",
        "What kind of transportation do people use in your hometown?",
        "Is there anything you dislike about your hometown?",
        "What is the weather like in your hometown?",
        "Are there many young people living in your hometown?",
        "Would you like to move to a different city one day?",
        "What facilities are available in your hometown?",
        "How do people in your hometown typically spend their weekends?",
        "Is your hometown a quiet or busy place?",
        "Do you think your hometown is a good place for children to grow up?",
        "What changes would you like to see in your hometown?",
        "How long have you been living in your current city?",
        "What is your favourite place to visit in your hometown?",
    ],
    "work or studies": [
        "Do you work or are you a student?",
        "What subject are you studying?",
        "Why did you choose that subject?",
        "What do you enjoy most about your studies?",
        "Is your job related to your studies?",
        "What are your responsibilities at work?",
        "Do you prefer working alone or in a team?",
        "What are the most challenging aspects of your job?",
        "Would you like to change your career in the future?",
        "How do you manage your time between work and personal life?",
        "What skills have you developed through your studies?",
        "Do you think your current job will be in demand in the future?",
        "What are the best things about being a student?",
        "How long have you been doing your current job?",
        "What would be your ideal job?",
        "Do you think it is important to enjoy your work?",
        "How has studying helped you in your daily life?",
        "Do you plan to continue studying after you graduate?",
    ],
    "hobbies": [
        "What do you like to do in your free time?",
        "How often do you practice your hobby?",
        "When did you first become interested in this hobby?",
        "Is your hobby expensive?",
        "Have you tried any new hobbies recently?",
        "Do you do your hobby alone or with other people?",
        "What benefits does your hobby bring to your life?",
        "Would you like to turn your hobby into a career?",
        "Has technology changed the way people enjoy hobbies?",
        "What hobbies are popular among young people in your country?",
        "Do children and adults tend to have the same hobbies?",
        "Did you have the same hobbies when you were a child?",
        "What is the most unusual hobby you have heard of?",
        "How do you feel when you cannot find time for your hobby?",
        "Have you ever taught someone else your hobby?",
        "Is it important to have a hobby? Why?",
        "Would you recommend your hobby to others?",
        "How much time a week do you spend on your hobby?",
    ],
    "travel": [
        "Do you enjoy travelling?",
        "How often do you travel?",
        "What was the last place you visited?",
        "Do you prefer travelling alone or with others?",
        "What do you like to do when you travel?",
        "Do you prefer domestic or international travel?",
        "What kind of accommodation do you prefer when travelling?",
        "Have you ever had a bad travel experience?",
        "What country would you most like to visit and why?",
        "Do you think travelling changes people's perspectives?",
        "How do you prepare for a trip?",
        "What do you usually bring when you travel?",
        "Do you like trying local food when you travel?",
        "What is the best place you have ever visited?",
        "Do you prefer relaxing holidays or adventure trips?",
        "How has travel technology changed the way people explore new places?",
        "Have you ever experienced culture shock while travelling?",
        "Is it important for children to travel? Why?",
    ],
    "food": [
        "Do you enjoy cooking?",
        "How often do you eat out?",
        "What is your favourite food?",
        "Do you prefer home-cooked meals or restaurant food?",
        "Have you ever tried food from a foreign country?",
        "What traditional foods are popular in your country?",
        "Do you think eating habits have changed in recent years?",
        "Is there any food you absolutely cannot eat?",
        "How important is it to eat healthily?",
        "Do you think fast food is popular in your country?",
        "What do you usually have for breakfast?",
        "Do you enjoy trying new foods?",
        "Have you ever cooked a meal for someone else?",
        "Do you think food is an important part of culture?",
        "How do people in your country typically celebrate special occasions with food?",
        "What is a typical meal in your household?",
        "Is food expensive in your city?",
        "Do you watch cooking shows? Why or why not?",
    ],
    "technology": [
        "How often do you use your smartphone?",
        "What apps do you use most frequently?",
        "Do you think people depend too much on technology?",
        "How has technology changed daily life in your country?",
        "Do you prefer reading news online or in print?",
        "What was the first technological device you ever owned?",
        "Do you think children should be allowed to use smartphones?",
        "How do you feel when your phone battery dies?",
        "What technology do you think will be most important in the future?",
        "Do you use social media? How often?",
        "Has technology made people more or less social, in your opinion?",
        "Do you think technology makes people lazier?",
        "What role does technology play in your work or studies?",
        "Have you ever tried using a smart home device?",
        "Do you prefer using technology or doing things manually?",
        "What is the most useful piece of technology in your daily life?",
        "Do you think technology has improved education?",
        "Are there any disadvantages of technology you have personally experienced?",
    ],
    "music": [
        "Do you enjoy listening to music?",
        "What kind of music do you like?",
        "Do you play any musical instruments?",
        "How often do you listen to music?",
        "When do you usually listen to music?",
        "Did you listen to the same type of music when you were younger?",
        "Do you prefer listening to music at home or at live concerts?",
        "Has a song ever changed your mood?",
        "Do you think music is an important part of culture?",
        "Is music popular among young people in your country?",
        "Do you think it is important to learn music at school?",
        "Do you have a favourite singer or band?",
        "Can you concentrate while listening to music?",
        "Do people in your country enjoy traditional music?",
        "How has streaming changed the way people listen to music?",
        "Have you ever been to a music festival?",
        "Do you think music can bring people together?",
        "What is the most memorable concert or performance you have attended?",
    ],
    "sports": [
        "Do you play any sports?",
        "What sports are popular in your country?",
        "Did you play sports as a child?",
        "Do you prefer team sports or individual sports?",
        "How often do you exercise?",
        "Do you enjoy watching sports on television?",
        "Have you ever been to a live sporting event?",
        "Do you think sport is important for children?",
        "What are the benefits of playing sports regularly?",
        "Have you ever tried an extreme sport?",
        "Is there a sport you would like to learn?",
        "Do you think professional athletes earn too much money?",
        "How has technology changed sport?",
        "Do you think your country performs well in international sports?",
        "What is the most popular sport in your hometown?",
        "Have you ever had a sports-related injury?",
        "Do you prefer outdoor or indoor sports?",
        "Why do you think some people do not like sport?",
    ],
    "family": [
        "Do you have a large or small family?",
        "Are you close to your family?",
        "How often do you spend time with your family?",
        "What do you usually do together as a family?",
        "Do you live with your family or independently?",
        "Who in your family are you closest to?",
        "Did you grow up in a big family?",
        "Do you think family relationships have changed in modern times?",
        "What is the most important thing your family has taught you?",
        "Do you think it is important to have family meals together?",
        "How do families in your country typically spend holidays?",
        "Do you have any family traditions?",
        "In your culture, how important is the extended family?",
        "Would you like to have a large or small family in the future?",
        "How has technology affected family communication?",
        "Do you think people today spend enough time with their families?",
        "What is a quality you admire in your family members?",
        "Do you think parents today have more or less influence over their children than before?",
    ],
    "environment": [
        "Are you interested in environmental issues?",
        "What environmental problems are most serious in your country?",
        "Do you do anything to help protect the environment?",
        "Do you think people are becoming more environmentally aware?",
        "What is your opinion on recycling?",
        "Have you noticed any changes in the climate where you live?",
        "Do you think individuals or governments are more responsible for protecting the environment?",
        "Would you pay more for eco-friendly products?",
        "How important is it to preserve natural habitats?",
        "What do you think about using public transport to reduce pollution?",
        "Have you ever participated in any environmental activities?",
        "Do you think technology can help solve environmental problems?",
        "Is the environment an important topic in your school or workplace?",
        "How do people in your country feel about environmental protection?",
        "What small habits can people adopt to help the environment?",
        "Do you think future generations will face more environmental challenges?",
        "Have you changed any habits recently to be more eco-friendly?",
        "Do you think economic development and environmental protection can coexist?",
    ],
}
